spring:
  application:
    name: coupons
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

app:
  external:
    country-api-url: https://api.country.is